
/* DO NOT EDIT - This file is autogenerated */

#ifndef COLORMATRIX_H
#define COLORMATRIX_H

#define NGLI_COLORMATRIX_UNDEFINED 0
#define NGLI_COLORMATRIX_BT601     1
#define NGLI_COLORMATRIX_BT709     2
#define NGLI_COLORMATRIX_BT2020    3

void ngli_colormatrix_yuv_to_rgb(float *dst, int colormatrix);

#endif
