
/* DO NOT EDIT - This file is autogenerated */

#include <string.h>

#include "colormatrix.h"

static const float colormatrices[][16] = {
    [NGLI_COLORMATRIX_BT601] = {
                   85/73.,                85/73.,            85/73., 0.,
                       0.,     -1287801/3287200.,      22593/11200., 0.,
             35751/22400.,   -10689549/13148800.,                0., 0.,
          -167519/191625.,   59804057/112483875.,   -208034/191625., 1.,
    },
    [NGLI_COLORMATRIX_BT709] = {
                   85/73.,                85/73.,            85/73., 0.,
                       0.,  -28469543/133504000.,    236589/112000., 0.,
           200787/112000.,  -71145527/133504000.,                0., 0.,
          -932203/958125.,   34431883/114208500.,  -1085941/958125., 1.,
    },
    [NGLI_COLORMATRIX_BT2020] = {
                   85/73.,                85/73.,            85/73., 0.,
                       0.,  -94831967/506240000.,    479757/224000., 0.,
           376023/224000., -329270807/506240000.,                0., 0.,
        -1754687/1916250.,  250791201/721787500., -2200133/1916250., 1.,
    },
};

void ngli_colormatrix_yuv_to_rgb(float *dst, int colormatrix)
{
    memcpy(dst, colormatrices[colormatrix], sizeof(colormatrices[colormatrix]));
}
